version: '2.1'
services:

  app2:
    container_name: app1
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=DC2
    depends_on:
      seed2:
        condition: service_healthy

  seed2:
    container_name: seed1
    build: ./cassandra
    environment:
      - DATACENTER=DC1
    ports:
      - 9042:9042
      - 7000:7000
    volumes:
      - seed2:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(/opt/cassandra/bin/nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 60s
      retries: 5

  node2:
    container_name: node1
    build: ./cassandra
    environment:
      - DATACENTER=DC2
    depends_on:
      - seed1
    volumes:
      - node1:/var/lib/cassandra


volumes:
  seed1:
  node1:
