version: '3.0'
services:

  app1:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=DC1
    restart: on-failure

  seed1:
    build: ./cassandra
    environment:
      - DATACENTER=DC1
    ports:
      - 9042:9042
      - 7000:7000
    volumes:
      - seed1:/var/lib/cassandra

  node1:
    build: ./cassandra
    environment:
      - DATACENTER=DC1
    depends_on:
      - seed1
    volumes:
      - node1:/var/lib/cassandra


volumes:
  seed1:
  node1:
